# Generated by Django 3.1.7 on 2021-02-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("drilling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f",
                    models.FloatField(help_text="f in mm/revolution", verbose_name="f"),
                ),
                ("vc", models.FloatField(help_text="vc in m/min", verbose_name="vc")),
            ],
        ),
        migrations.AlterField(
            model_name="drill",
            name="flute_count",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name="DrillRecipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rpm_override",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RPM Override"
                    ),
                ),
                (
                    "vf_override",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Vf Override"
                    ),
                ),
                (
                    "drill_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drilling.drilldata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drilldata",
            name="drill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="drilling.drill"
            ),
        ),
        migrations.AddField(
            model_name="drilldata",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="materials.material"
            ),
        ),
    ]
