# Generated by Django 3.1.7 on 2021-02-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0003_auto_20210221_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='drill_type',
            field=models.CharField(choices=[('SPIRAL_DRILL', 'Spiral Drill'), ('SPOT_DRILL', 'Spot Drill')], default='SPIRAL_DRILL', max_length=20),
        ),
    ]
