# Generated by Django 3.1.7 on 2021-02-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drilling", "0004_auto_20210222_1724"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drill",
            options={"ordering": ("diameter",)},
        ),
        migrations.RemoveField(
            model_name="drill",
            name="flute_count",
        ),
        migrations.RemoveField(
            model_name="drill",
            name="name",
        ),
        migrations.RemoveField(
            model_name="drill",
            name="tip_angle",
        ),
    ]
