# Generated by Django 3.1.7 on 2021-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milling", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ("vendor", "diameter")},
        ),
    ]
