# Generated by Django 3.1.7 on 2021-02-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milling", "0002_auto_20210220_2024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="name",
        ),
    ]
