# Generated by Django 3.1.7 on 2021-02-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milling", "0003_remove_tool_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_number", models.PositiveIntegerField()),
                (
                    "tool_length",
                    models.FloatField(
                        help_text="Overall tool length (including tool holder) from spindle 0."
                    ),
                ),
                (
                    "tool_diameter_override",
                    models.FloatField(
                        help_text="Tool diameter override to compensate tool wear."
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_table_entry",
                        to="milling.tool",
                    ),
                ),
            ],
            options={
                "ordering": ("tool_number",),
            },
        ),
    ]
