# Generated by Django 3.1.7 on 2021-02-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milling", "0006_auto_20210226_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tooltableentry",
            options={
                "ordering": ("t",),
                "verbose_name": "Tool Table Entry",
                "verbose_name_plural": "Tool Table Entries",
            },
        ),
        migrations.RenameField(
            model_name="tooltableentry",
            old_name="tool_diameter_override",
            new_name="d",
        ),
        migrations.RenameField(
            model_name="tooltableentry",
            old_name="tool_number",
            new_name="t",
        ),
        migrations.RenameField(
            model_name="tooltableentry",
            old_name="tool_length",
            new_name="z",
        ),
        migrations.AddField(
            model_name="tooltableentry",
            name="name",
            field=models.CharField(default="tool", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tooltableentry",
            name="tool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_table_entry",
                to="milling.tool",
            ),
        ),
    ]
